---
title: "Boulder Flood"
author: "Jeff Atkins"
date: "June 22, 2016"
output: html_document
---

```{r import-libraries}
library(raster)
library(rgdal)
```


```{r import-rasters}

# importing pre and post flood  digital surface rasters
pre.dsm <- raster("../NEONdata/Boulder_Flood/BLDR_LeeHill_Pre_Post_Flood/pre-flood/BLDR_pre_DSM/preDSM3.tif")

post.dsm <- raster("../NEONdata/Boulder_Flood/BLDR_LeeHill_Pre_Post_Flood/post-flood/postDSM/postDSM3.tif")

# importing pre and post flood digital terrain models

pre.dtm <- raster("../NEONdata/Boulder_Flood/BLDR_LeeHill_Pre_Post_Flood/pre-flood/BLDR_pre_DTM/preDTM3.tif")

post.dtm <- raster("../NEONdata/Boulder_Flood/BLDR_LeeHill_Pre_Post_Flood/post-flood/postDTM/postDTM3.tif")

pre.camera <- raster("../NEONdata/Boulder_Flood/BLDR_LeeHill_Pre_Post_Flood/pre-flood/BLDR_pre_camera/preCamera_Comp.tif")

plot(pre.camera)
```

## Vegetation loss from flooding
```{r get-simple-CHM}
# We want to make simple Canopy Height Models of pre- and post-flooding
post_chm <- post.dsm - post.dtm
# 0 values as NA
post_chm[post_chm == 0] <- NA

pre_chm <- pre.dsm - pre.dtm
# 0 values as NA
pre_chm[pre_chm == 0] <- NA

```

```{r check-pre-post-veg-diff}
# Subtract post- from pre-flooding to evaluate veg loss
chm_diff <- pre_chm - post_chm

# Lots of noise. Let's get rid of it.
chm_diff[chm_diff > -1] <- NA

```

```{r plot-diff}
plot(chm_diff,
     col = rev(rainbow(40, start = .6)))
```

